first commit
electron/release-status pull request #61
Opened 2024-09-14 09:38 UTC by omkar200412

some changes of ui/ux and color

2024-09-14 09:42 UTC, MarshallOfSound requested changes
What is the purpose of this change, is their a bug somewhere or a UX / A11Y issue you're trying to fix?

2024-09-14 15:28 UTC, omkar200412 reviewed
some changes in ui/ux nad colors

2024-09-14 15:28 UTC, omkar200412 commented
some changes of ui/ux color

2024-09-14 15:50 UTC, omkar200412 commented on package.json
> +    "dev": "nodemon index.js"
Is there are some npm issue or I'm not able to open this project in web so I'll try Nodemon then issue solved

2024-09-14 21:14 UTC, codebytere commented
Closing as invalid.

2024-09-14 21:14 UTC, closed without merging

2024-09-15 05:30 UTC, omkar200412 commented
ok No problem I'll come Next time  with New bug